  version: '2'

  services:

    #PHP Service
    phpa:
      container_name: phpa
      build:
        context: .
        dockerfile: Dockerfile-php
      working_dir: /var/www/laravel
      restart: unless-stopped
      ports:
        - "9002:9000"
      volumes:
        - ./:/var/www/laravel
      networks:
        - app-network

    #Nginx Service
    webserva:
      container_name: webserva
      image: nginx:latest
      working_dir: /var/www/laravel
      restart: unless-stopped
      ports:
        - "9082:80"
        - "4432:443"
      volumes:
        - ./:/var/www/laravel
        - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./docker/nginx/log/:/var/log/nginx/
      networks:
        - app-network

    #MySQL Service
    dba:
      container_name: dba
      image: mysql:5.7
      restart: unless-stopped
      ports:
        - "3309:3306"
      environment:
        MYSQL_DATABASE: studiqa
        MYSQL_ROOT_PASSWORD: password
      networks:
        - app-network


  #Docker Networks
  networks:
    app-network:
      driver: bridge




